---
page_title:
  title: Alertas y notificaciones
  content: 'Alertas y Notificaciones : son notificaciones automáticas por correo electrónico enviadas a los agentes cuando se activan varios eventos de Ordenes de Servicio.'
ticket_alert:
  title: Aviso de nueva Orden de Servicio
  content: '<p>Alerta enviada a los agentes cuando se crea una nueva Orden de Servicio.</p><p class="info-banner"> <i class="icon-info-sign"></i> Esta alerta no se envía si la Orden de Servicio es auto asignada mediante un Filtro de Orden de Servicio o Tema de Ayuda.</p>'
  links:
    - 
      title: Plantilla Predeterminada de alerta para Nueva Orden de Servicio
      href: /scp/templates.php?default_for=ticket.alert
message_alert:
  title: Aviso de nuevo mensaje
  content: Alerta enviada a Agentes cuando un nuevo mensaje del usuario se agrega a una Orden de Servicio existente.
  links:
    - 
      title: 'Plantilla  para Alerta de Nuevo Mensaje'
      href: /scp/templates.php?default_for=message.alert
internal_note_alert:
  title: Alerta de nueva actividad interna
  content: Alerta es enviada a los agentes cuando una actividad interna como nota interna o respuesta de agente es agregado a la orden de Servicio.
  links:
    - 
      title: Plantilla predeterminada de la actividad de una Orden de Servicio
      href: /scp/templates.php?default_for=note.alert
assignment_alert:
  title: Aviso de asignación de Orden de Servicio
  content: Alerta enviada a agentes por asignación de una Orden de Servicio.
  links:
    - 
      title: Plantilla por defecto de Alerta de Asignación de Orden de Servicio
      href: /scp/templates.php?default_for=assigned.alert
transfer_alert:
  title: Alerta al transferir una orden de Servicio
  content: Alerta enviada a los agentes por la transferencia de una Orden de Servicio entre departamentos.
  links:
    - 
      title: Plantilla por defecto para transferencias de Ordenes de Servicio
      href: /scp/templates.php?default_for=transfer.alert
overdue_alert:
  title: Alerta de Orden de Servicio retrasado
  content: 'Alerta enviada a agentes cuando una orden de Servicio se convierte en atrasado según el Acuerdo de Nivel de Servicio -SLA- o su fecha de vencimiento.'
  links:
    - 
      title: 'Plantilla Predeterminada para Ordenes de Servicio Caducadas'
      href: /scp/templates.php?default_for=ticket.overdue
    - 
      title: Gestionar Niveles de Servicio
      href: /scp/slas.php
system_alerts:
  title: Alertas del Sistema
  content: 'Eventos significativos del sistema que se envían al administrador (%{config.admin_email}). Dependiendo de lo configurado en el <span class="doc-desc-title">Nivel de registro</span>, los eventos también estarán disponibles en los <span class="doc-desc-title">Registros del sistema</span>'
  links:
    - 
      title: Ver registros del sistema
      href: /scp/logs.php
    - 
      title: Cambiar email de Administrador
      href: /scp/settings.php?t=emails
