---
new_ticket:
  title: Nueva Orden de Servicio
  content: Marque esto si desea una autorespuesta al enviarse al usuario en una nueva Orden de Servicio.
  links:
    - 
      title: Plantilla de Respuesta automática de una Nueva Orden de Servicio
      href: /scp/templates.php?default_for=ticket.autoresp
new_ticket_by_staff:
  title: Nueva Orden de Servicio por el personal
  content: 'Aviso enviado cuando un agente crea una Orden de Servicio en nombre del usuario. <em>El agente puede reemplazar esto al crear nuevas Ordenes de Servicio.</em>'
  links:
    - 
      title: Nueva plantilla de aviso de Orden de Servicio
      href: /scp/templates.php?default_for=ticket.notice
new_message_for_submitter:
  title: Confirmación de Nuevo Mensaje
  content: Aviso de confirmación enviado cuando un nuevo mensaje se anexa a una Orden de Servicio existente.
  links:
    - 
      title: Nueva plantilla de mensaje de confirmación
      href: /scp/templates.php?default_for=message.autoresp
new_message_for_participants:
  title: Nueva notificación de mensaje
  content: Difusión de los mensajes recibidos del remitente del mensaje a todos los demás participantes en la Orden de Servicio.
  links:
    - 
      title: Nueva plantilla de aviso de actividad
      href: /scp/templates.php?default_for=ticket.activity.notice
overlimit_notice:
  title: Aviso de limite sobrepasado
  content: 'Aviso de Orden de Servicio denegado enviado al usuario en<span class="doc-desc-title"> Máxima apertura de violación de Orden de Servicio</span>.'
  links:
    - 
      title: Plantilla de aviso de sobrepasado
      href: /scp/templates.php?default_for=ticket.overlimit
    - 
      title: 'Establecer la <em>máxima apertura de Orden de Servicio</em>'
      href: /scp/settings?t=tickets
